---
name: Release
'on':
  push:
    tags:
      - '*'
jobs:
  release:
    name: Create Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-10.15
            shasum: shasum -a 512
          - os: ubuntu-20.04
            shasum: sha512sum
          - os: windows-2019
            shasum: sha512sum
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.0
      # yamllint disable rule:line-length
      - name: Set LOGGING deliverable environment variable
        run: echo "logging-deliverable=logging-${{ matrix.os }}" >> $GITHUB_ENV
        if: |
          ${{ startsWith(matrix.os, 'mac') || startsWith(matrix.os, 'ubuntu') }}
      - name: Set LOGGING deliverable environment variable on Windows
        run: echo "logging-deliverable=logging-${{ matrix.os }}" >> $env:GITHUB_ENV
        if: ${{ startsWith(matrix.os, 'windows') }}go
      - name: Use the value
        run: |
          echo "${{ env.logging-deliverable }}"
      - name: Check whether all versions have been updated
        run: |
          version=$(echo "${{ github.ref }}" | sed -e "s|.*\/\(.*\)$|\1|")
          echo "Version: ${version}"
          echo "Checking build/package/snap/snapcraft.yaml..."
          grep ${version} build/package/snap/snapcraft.yaml
          echo "Checking README.md..."
          grep "logging:${version}" README.md
        if: ${{ startsWith(matrix.os, 'mac') || startsWith(matrix.os, 'ubuntu') }}
      - name: Create release
        run: ./scripts/build.sh
        env:
          LOGGING_DELIVERABLE: ${{ env.logging-deliverable }}
          GITHUB_TAG: ${{ github.ref }}
          SHA512_CMD: ${{ matrix.shasum }}
        if: ${{ startsWith(matrix.os, 'mac') || startsWith(matrix.os, 'ubuntu') }}
      - name: Create release windows
        shell: cmd
        run: |
          echo "GITHUB_TAG: '${{ github.ref }}'"
          echo "LOGGING_DELIVERABLE: '${{ env.logging-deliverable }}'"
          cd cmd/logging
          go build -buildvcs=false -ldflags "-X main.Version=${{ github.ref }}" -o "${{ env.logging-deliverable }}"
          sha512sum "${{ env.logging-deliverable }}" > "${{ env.logging-deliverable }}.sha512.txt"
          chmod +x "${{ env.logging-deliverable }}"
          ls logging-windows-2019
        if: ${{ startsWith(matrix.os, 'windows') }}
      # yamllint enable rule:line-length
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cmd/logging/${{ env.logging-deliverable }}
          asset_name: ${{ env.logging-deliverable }}
          tag: ${{ github.ref }}
      - name: Upload checksums
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: cmd/logging/${{ env.logging-deliverable }}.sha512.txt
          asset_name: ${{ env.logging-deliverable }}.sha512.txt
          tag: ${{ github.ref }}
